# Generated by Django 4.2 on 2024-08-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_precio_total_compra_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='precio',
            new_name='total',
        ),
    ]
